huh:
  encore:
    entries:
      - { name: contao-youtube-bundle, file: "vendor/heimrichhannot/contao-youtube-bundle/src/Resources/assets/js/contao-youtube-bundle.js" }
      - { name: contao-youtube-bundle-theme, requiresCss: true, file: "vendor/heimrichhannot/contao-youtube-bundle/src/Resources/public/js/contao-youtube-bundle.js" }
    legacy:
      js:
        - contao-youtube-bundle
        - umbrellajs
        - bootbox
      css:
        - contao-youtube-bundle